#!/bin/bash

sbatch ./finetune-eng-spa-senti.sh --train-lang="english" --model-type="normal"
sbatch ./finetune-eng-spa-senti.sh --train-lang="spanish" --model-type="normal"
sbatch ./finetune-eng-spa-senti.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-eng-spa-senti.sh --train-lang="english" --model-type="ipa"
sbatch ./finetune-eng-spa-senti.sh --train-lang="spanish" --model-type="ipa"
sbatch ./finetune-eng-spa-senti.sh --train-lang="both" --model-type="ipa"

sbatch ./finetune-eng-spa-entail.sh --train-lang="english" --model-type="normal"
sbatch ./finetune-eng-spa-entail.sh --train-lang="spanish" --model-type="normal"
sbatch ./finetune-eng-spa-entail.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-eng-spa-entail.sh --train-lang="english" --model-type="ipa"
sbatch ./finetune-eng-spa-entail.sh --train-lang="spanish" --model-type="ipa"
sbatch ./finetune-eng-spa-entail.sh --train-lang="both" --model-type="ipa"

sbatch ./finetune-eng-spa-qa.sh --train-lang="english" --model-type="normal"
sbatch ./finetune-eng-spa-qa.sh --train-lang="spanish" --model-type="normal"
sbatch ./finetune-eng-spa-qa.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-eng-spa-qa.sh --train-lang="english" --model-type="ipa"
sbatch ./finetune-eng-spa-qa.sh --train-lang="spanish" --model-type="ipa"
sbatch ./finetune-eng-spa-qa.sh --train-lang="both" --model-type="ipa"

sbatch ./finetune-rus-pol-senti.sh --train-lang="russian" --model-type="normal"
sbatch ./finetune-rus-pol-senti.sh --train-lang="spanish" --model-type="normal"
sbatch ./finetune-rus-pol-senti.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-rus-pol-senti.sh --train-lang="russian" --model-type="ipa"
sbatch ./finetune-rus-pol-senti.sh --train-lang="spanish" --model-type="ipa"
sbatch ./finetune-rus-pol-senti.sh --train-lang="both" --model-type="ipa"

sbatch ./finetune-rus-pol-entail.sh --train-lang="russian" --model-type="normal"
sbatch ./finetune-rus-pol-entail.sh --train-lang="polish" --model-type="normal"
sbatch ./finetune-rus-pol-entail.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-rus-pol-entail.sh --train-lang="russian" --model-type="ipa"
sbatch ./finetune-rus-pol-entail.sh --train-lang="polish" --model-type="ipa"
sbatch ./finetune-rus-pol-entail.sh --train-lang="both" --model-type="ipa"

sbatch ./finetune-rus-pol-qa.sh --train-lang="russian" --model-type="normal"
sbatch ./finetune-rus-pol-qa.sh --train-lang="polish" --model-type="normal"
sbatch ./finetune-rus-pol-qa.sh --train-lang="both" --model-type="normal"
sbatch ./finetune-rus-pol-qa.sh --train-lang="russian" --model-type="ipa"
sbatch ./finetune-rus-pol-qa.sh --train-lang="polish" --model-type="ipa"
sbatch ./finetune-rus-pol-qa.sh --train-lang="both" --model-type="ipa"
